spack install cfastc@7.7.4%oneapi
spack install cfastc@7.7.4%oneapi
spack install cfastc@7.7.3%oneapi
spack install cfastc@7.7.2%oneapi
spack install cfastc@7.7.1%oneapi
spack install cfastc@7.7.0%oneapi
spack install cfastc@7.5.2%oneapi
spack install cfastc@7.5.1%oneapi
spack install cfastc@7.4.3%oneapi
spack install cfastc@7.4.2%oneapi
spack install cfastc@7.4.0%oneapi
spack install cfastc@7.3.1%oneapi
spack install cfastc@7.3.0%oneapi
spack install cfastc@7.2.4%oneapi
spack install cfastc@7.2.3%oneapi
spack install cfastc@7.2.2%oneapi
spack install cfastc@7.2.1%oneapi
spack install cfastc@7.2.0%oneapi
spack install cfastc@7.1.2%oneapi
spack install cfastc@7.1.1%oneapi
spack install cfastc@7.1.0%oneapi
spack install cfastc@7.0.1%oneapi
