#!/bin/bash
pacman -R fds-6.7.5+nist.ifort 
pacman -R fds-6.7.4+nist.ifort 
pacman -R fds-6.7.3+nist.ifort 
pacman -R fds-6.7.1+nist.ifort 
pacman -R fds-6.7.0+nist.ifort 
pacman -R fds-6.6.0+nist.ifort 
pacman -R fds-6.5.3+nist.ifort 
pacman -R fds-6.5.2+nist.ifort 
pacman -R fds-6.5.1+nist.ifort 
pacman -R fds-6.5.0+nist.ifort 
pacman -R fds-6.4.0+nist.ifort 
pacman -R fds-6.3.2+nist.ifort 
pacman -R fds-6.3.1+nist.ifort 
pacman -R fds-6.3.0+nist.ifort 
pacman -R fds-6.2.0+nist.ifort 
pacman -R fds-6.1.2+nist.ifort 
pacman -R fds-5.5.3+nist.ifort 
pacman -R fds-6.7.7+smokecloud.ifort 
pacman -R fds-6.7.6+smokecloud.ifort 
pacman -R fds-6.7.5+smokecloud.ifort 
pacman -R fds-6.7.4+smokecloud.ifort 
pacman -R fds-6.7.3+smokecloud.ifort 
pacman -R fds-6.7.1+smokecloud.ifort 
pacman -R fds-6.7.0+smokecloud.ifort 
pacman -R fds-6.6.0+smokecloud.ifort 
pacman -R fds-6.5.3+smokecloud.ifort 
pacman -R fds-6.5.2+smokecloud.ifort 
pacman -R fds-6.5.1+smokecloud.ifort 
pacman -R fds-6.5.0+smokecloud.ifort 
pacman -R fds-6.4.0+smokecloud.ifort 
pacman -R fds-6.3.2+smokecloud.ifort 
pacman -R fds-6.3.1+smokecloud.ifort 
pacman -R fds-6.3.0+smokecloud.ifort 
pacman -R fds-6.2.0+smokecloud.ifort 
pacman -R fds-6.1.2+smokecloud.ifort
pacman -R fds-5.5.3+smokecloud.ifort
