# Generated by rust2rpm 27
%bcond check 1

# prevent library files from being installed
%global cargo_install_lib 0

Name:           fdspp
Version:        0.3.2
Release:        %autorelease
Summary:        # FIXME

SourceLicense:  GPL-2.0-or-later
# FIXME: paste output of %%cargo_license_summary here
License:        GPL-2.0-or-later
# LICENSE.dependencies contains a full license breakdown
%global commit 96540d5daa5b5c2adcdaa1171f73a16e963b4a63

Source:        https://github.com/Smoke-Cloud/fdspp/archive/%{commit}.zip
Url:           https://github.com/Smoke-Cloud/fdspp

BuildRequires:  cargo-rpm-macros >= 26

%global _description %{expand:
%{summary}.}

%description %{_description}

%prep
%autosetup -n fdspp-%{commit} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files
# FIXME: no license files detected
%license LICENSE.dependencies
%doc README.md
%{_bindir}/fdspp

%changelog
%autochangelog
